"""add reel_transcriptions table

Revision ID: 2477721df2fe
Revises: f2e9cc286919
Create Date: 2026-07-30 11:15:20.556470

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '2477721df2fe'
down_revision: str | None = 'f2e9cc286919'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reel_transcriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reel_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('dominant_language', sa.String(length=16), nullable=True),
    sa.Column('languages_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('words_json', sa.JSON(), nullable=True),
    sa.Column('utterances_json', sa.JSON(), nullable=True),
    sa.Column('paragraphs_json', sa.JSON(), nullable=True),
    sa.Column('provider_request_id', sa.String(length=64), nullable=True),
    sa.Column('provider_duration', sa.Float(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], name=op.f('fk_reel_transcriptions_reel_id_reels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reel_transcriptions')),
    sa.UniqueConstraint('reel_id', name='uq_reel_transcriptions_reel_id')
    )
    with op.batch_alter_table('reel_transcriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reel_transcriptions_reel_id'), ['reel_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_reel_transcriptions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reel_transcriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reel_transcriptions_status'))
        batch_op.drop_index(batch_op.f('ix_reel_transcriptions_reel_id'))

    op.drop_table('reel_transcriptions')
    # ### end Alembic commands ###
