"""Add ReelAnalysis

Revision ID: 531cddffad16
Revises: 2477721df2fe
Create Date: 2026-07-30 12:32:40.295142

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '531cddffad16'
down_revision: str | None = '2477721df2fe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reel_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reel_id', sa.Integer(), nullable=False),
    sa.Column('transcription_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('requested_model', sa.String(length=128), nullable=False),
    sa.Column('resolved_model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('source_language', sa.String(length=16), nullable=True),
    sa.Column('russian_transcript', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('hook_json', sa.JSON(), nullable=True),
    sa.Column('main_part_json', sa.JSON(), nullable=True),
    sa.Column('conclusion_json', sa.JSON(), nullable=True),
    sa.Column('cta_json', sa.JSON(), nullable=True),
    sa.Column('suggested_hook', sa.Text(), nullable=True),
    sa.Column('suggested_script', sa.Text(), nullable=True),
    sa.Column('suggested_cta', sa.Text(), nullable=True),
    sa.Column('usage_prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('usage_completion_tokens', sa.Integer(), nullable=True),
    sa.Column('usage_reasoning_tokens', sa.Integer(), nullable=True),
    sa.Column('usage_total_tokens', sa.Integer(), nullable=True),
    sa.Column('provider_request_id', sa.String(length=128), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], name=op.f('fk_reel_analyses_reel_id_reels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcription_id'], ['reel_transcriptions.id'], name=op.f('fk_reel_analyses_transcription_id_reel_transcriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reel_analyses')),
    sa.UniqueConstraint('reel_id', name='uq_reel_analyses_reel_id')
    )
    with op.batch_alter_table('reel_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reel_analyses_reel_id'), ['reel_id'], unique=True)
        batch_op.create_index('ix_reel_analyses_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reel_analyses_transcription_id'), ['transcription_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reel_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reel_analyses_transcription_id'))
        batch_op.drop_index('ix_reel_analyses_status')
        batch_op.drop_index(batch_op.f('ix_reel_analyses_reel_id'))

    op.drop_table('reel_analyses')
    # ### end Alembic commands ###
