"""add YouTube monitoring MVP
Revision ID: 8c0b2e1a4f7d
Revises: 2477721df2fe
"""
from alembic import op
import sqlalchemy as sa

revision = "8c0b2e1a4f7d"
down_revision = "531cddffad16"
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("monitoring_topics", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.String(128), nullable=False), sa.Column("name", sa.String(160), nullable=False), sa.Column("keywords", sa.JSON(), nullable=False), sa.Column("negative_keywords", sa.JSON(), nullable=False), sa.Column("language", sa.String(16)), sa.Column("region_code", sa.String(8)), sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False), sa.Column("minimum_score", sa.Integer(), server_default="70", nullable=False), sa.Column("check_interval_hours", sa.Integer(), server_default="3", nullable=False), sa.Column("last_checked_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False), sa.UniqueConstraint("user_id", "name", name="uq_monitoring_topics_user_name"))
    op.create_index("ix_monitoring_topics_user_id", "monitoring_topics", ["user_id"])
    op.create_table("monitored_channels", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.String(128), nullable=False), sa.Column("monitoring_topic_id", sa.Integer()), sa.Column("platform", sa.String(32), server_default="youtube", nullable=False), sa.Column("channel_id", sa.String(64), nullable=False), sa.Column("channel_url", sa.String(500), nullable=False), sa.Column("channel_title", sa.String(255), nullable=False), sa.Column("thumbnail_url", sa.String(2000)), sa.Column("uploads_playlist_id", sa.String(64)), sa.Column("subscriber_count", sa.Integer()), sa.Column("last_checked_at", sa.DateTime(timezone=True)), sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False), sa.ForeignKeyConstraint(["monitoring_topic_id"], ["monitoring_topics.id"], ondelete="CASCADE"), sa.UniqueConstraint("user_id", "channel_id", name="uq_monitored_channels_user_channel"))
    op.create_index("ix_monitored_channels_user_id", "monitored_channels", ["user_id"]); op.create_index("ix_monitored_channels_channel_id", "monitored_channels", ["channel_id"])
    op.create_table("monitored_videos", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("platform", sa.String(32), server_default="youtube", nullable=False), sa.Column("external_id", sa.String(64), nullable=False), sa.Column("url", sa.String(500), nullable=False), sa.Column("title", sa.Text(), nullable=False), sa.Column("description", sa.Text()), sa.Column("channel_id", sa.String(64), nullable=False), sa.Column("channel_title", sa.String(255), nullable=False), sa.Column("thumbnail_url", sa.String(2000)), sa.Column("published_at", sa.DateTime(timezone=True), nullable=False), sa.Column("duration_seconds", sa.Integer()), sa.Column("content_type", sa.String(16), server_default="unknown", nullable=False), sa.Column("view_count", sa.Integer(), server_default="0", nullable=False), sa.Column("like_count", sa.Integer()), sa.Column("comment_count", sa.Integer()), sa.Column("views_per_hour", sa.Float()), sa.Column("engagement_rate", sa.Float()), sa.Column("relevance_score", sa.Float()), sa.Column("velocity_score", sa.Float()), sa.Column("engagement_score", sa.Float()), sa.Column("competitor_score", sa.Float()), sa.Column("ai_score", sa.Float()), sa.Column("final_score", sa.Float()), sa.Column("category", sa.String(64)), sa.Column("hook", sa.Text()), sa.Column("format", sa.String(255)), sa.Column("target_audience", sa.String(255)), sa.Column("why_it_works", sa.JSON()), sa.Column("recommendation", sa.Text()), sa.Column("status", sa.String(16), server_default="new", nullable=False), sa.Column("first_detected_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False), sa.Column("last_statistics_update_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False), sa.UniqueConstraint("platform", "external_id", name="uq_monitored_videos_platform_external"))
    op.create_index("ix_monitored_videos_channel_id", "monitored_videos", ["channel_id"]); op.create_index("ix_monitored_videos_published", "monitored_videos", ["published_at"])
    op.create_table("monitoring_topic_videos", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("topic_id", sa.Integer(), nullable=False), sa.Column("video_id", sa.Integer(), nullable=False), sa.Column("is_relevant", sa.Boolean(), server_default="1", nullable=False), sa.Column("notified_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False), sa.ForeignKeyConstraint(["topic_id"], ["monitoring_topics.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["video_id"], ["monitored_videos.id"], ondelete="CASCADE"), sa.UniqueConstraint("topic_id", "video_id", name="uq_topic_video"))
    op.create_index("ix_monitoring_topic_videos_topic_id", "monitoring_topic_videos", ["topic_id"]); op.create_index("ix_monitoring_topic_videos_video_id", "monitoring_topic_videos", ["video_id"])
    op.create_table("video_statistics_snapshots", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("video_id", sa.Integer(), nullable=False), sa.Column("view_count", sa.Integer(), server_default="0", nullable=False), sa.Column("like_count", sa.Integer()), sa.Column("comment_count", sa.Integer()), sa.Column("recorded_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False), sa.ForeignKeyConstraint(["video_id"], ["monitored_videos.id"], ondelete="CASCADE")); op.create_index("ix_video_statistics_snapshots_video_id", "video_statistics_snapshots", ["video_id"]); op.create_index("ix_video_statistics_snapshots_recorded_at", "video_statistics_snapshots", ["recorded_at"])
    op.create_table("youtube_quota_logs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("operation", sa.String(64), nullable=False), sa.Column("estimated_cost", sa.Integer(), nullable=False), sa.Column("metadata_json", sa.JSON()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False))

def downgrade():
    for table in ("youtube_quota_logs", "video_statistics_snapshots", "monitoring_topic_videos", "monitored_videos", "monitored_channels", "monitoring_topics"): op.drop_table(table)
