"""initial backend schema

Revision ID: f2e9cc286919
Revises: 
Create Date: 2026-07-26 17:27:58.993539

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f2e9cc286919'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instagram_username', sa.String(length=30), nullable=False),
    sa.Column('profile_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('idle', 'queued', 'parsing', 'ready', 'error', name='competitor_status', native_enum=False, length=16), server_default='idle', nullable=False),
    sa.Column('reels_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitors'))
    )
    with op.batch_alter_table('competitors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitors_instagram_username'), ['instagram_username'], unique=True)

    op.create_table('parsing_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('apify_run_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='parsing_job_status', native_enum=False, length=16), server_default='queued', nullable=False),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reels_created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reels_updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_parsing_jobs_competitor_id_competitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parsing_jobs'))
    )
    with op.batch_alter_table('parsing_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_parsing_jobs_competitor_id', ['competitor_id'], unique=False)
        batch_op.create_index('ix_parsing_jobs_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_parsing_jobs_status', ['status'], unique=False)

    op.create_table('reels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('instagram_id', sa.String(length=64), nullable=True),
    sa.Column('shortcode', sa.String(length=64), nullable=True),
    sa.Column('original_url', sa.String(length=1000), nullable=True),
    sa.Column('video_url', sa.String(length=2000), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2000), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_reels_competitor_id_competitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reels')),
    sa.UniqueConstraint('competitor_id', 'shortcode', name='uq_reels_competitor_shortcode')
    )
    with op.batch_alter_table('reels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reels_competitor_id'), ['competitor_id'], unique=False)
        batch_op.create_index('ix_reels_competitor_instagram_id', ['competitor_id', 'instagram_id'], unique=False)

    op.create_table('reel_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reel_id', sa.Integer(), nullable=False),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('cta', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('content_status', sa.Enum('new', 'idea', 'script', 'ready', 'published', 'archived', name='content_status', native_enum=False, length=16), server_default='new', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], name=op.f('fk_reel_content_reel_id_reels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reel_content'))
    )
    with op.batch_alter_table('reel_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reel_content_reel_id'), ['reel_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reel_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reel_content_reel_id'))

    op.drop_table('reel_content')
    with op.batch_alter_table('reels', schema=None) as batch_op:
        batch_op.drop_index('ix_reels_competitor_instagram_id')
        batch_op.drop_index(batch_op.f('ix_reels_competitor_id'))

    op.drop_table('reels')
    with op.batch_alter_table('parsing_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_parsing_jobs_status')
        batch_op.drop_index('ix_parsing_jobs_created_at')
        batch_op.drop_index('ix_parsing_jobs_competitor_id')

    op.drop_table('parsing_jobs')
    with op.batch_alter_table('competitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitors_instagram_username'))

    op.drop_table('competitors')
    # ### end Alembic commands ###
